# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Анна\Desktop\diplom\dip.rab3\form_set3.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Set_poll(object):
    def setupUi(self, Set_poll):
        Set_poll.setObjectName("Set_poll")
        Set_poll.resize(402, 382)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\Анна\\Desktop\\diplom\\dip.rab3\\science.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Set_poll.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Set_poll)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 131, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.set_x = QtWidgets.QTextEdit(self.centralwidget)
        self.set_x.setGeometry(QtCore.QRect(180, 10, 211, 31))
        self.set_x.setObjectName("set_x")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 50, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 90, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 10, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.set_y = QtWidgets.QTextEdit(self.centralwidget)
        self.set_y.setGeometry(QtCore.QRect(180, 50, 211, 31))
        self.set_y.setObjectName("set_y")
        self.set_z = QtWidgets.QTextEdit(self.centralwidget)
        self.set_z.setGeometry(QtCore.QRect(180, 90, 211, 31))
        self.set_z.setObjectName("set_z")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 200, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.set_y_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.set_y_2.setGeometry(QtCore.QRect(180, 240, 211, 31))
        self.set_y_2.setObjectName("set_y_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(130, 280, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.set_x_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.set_x_2.setGeometry(QtCore.QRect(180, 200, 211, 31))
        self.set_x_2.setObjectName("set_x_2")
        self.set_z_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.set_z_2.setGeometry(QtCore.QRect(180, 280, 211, 31))
        self.set_z_2.setObjectName("set_z_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(130, 240, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(130, 200, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.save_set = QtWidgets.QPushButton(self.centralwidget)
        self.save_set.setGeometry(QtCore.QRect(110, 320, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.save_set.setFont(font)
        self.save_set.setObjectName("save_set")
        self.set_Formyl = QtWidgets.QTextEdit(self.centralwidget)
        self.set_Formyl.setGeometry(QtCore.QRect(130, 130, 261, 51))
        self.set_Formyl.setObjectName("set_Formyl")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 120, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        Set_poll.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Set_poll)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 402, 21))
        self.menubar.setObjectName("menubar")
        Set_poll.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Set_poll)
        self.statusbar.setObjectName("statusbar")
        Set_poll.setStatusBar(self.statusbar)

        self.retranslateUi(Set_poll)
        QtCore.QMetaObject.connectSlotsByName(Set_poll)

    def retranslateUi(self, Set_poll):
        _translate = QtCore.QCoreApplication.translate
        Set_poll.setWindowTitle(_translate("Set_poll", "Ввод данных"))
        self.label_2.setToolTip(_translate("Set_poll", "Если задано уравнение, то данные будуь игнорироваться"))
        self.label_2.setText(_translate("Set_poll", "Размерность \n"
"паралле-\n"
"лепипеда \n"
" загрязнения"))
        self.set_x.setHtml(_translate("Set_poll", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">10</p></body></html>"))
        self.label_3.setText(_translate("Set_poll", "по Y"))
        self.label_4.setText(_translate("Set_poll", "по Z"))
        self.label.setText(_translate("Set_poll", "по X"))
        self.set_y.setHtml(_translate("Set_poll", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">10</p></body></html>"))
        self.set_z.setHtml(_translate("Set_poll", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">10</p></body></html>"))
        self.label_5.setToolTip(_translate("Set_poll", "Смещение загрязнения"))
        self.label_5.setText(_translate("Set_poll", "Смещение \n"
" относительно \n"
" центра"))
        self.set_y_2.setHtml(_translate("Set_poll", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>"))
        self.label_6.setText(_translate("Set_poll", "по Z"))
        self.set_x_2.setHtml(_translate("Set_poll", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>"))
        self.set_z_2.setHtml(_translate("Set_poll", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>"))
        self.label_7.setText(_translate("Set_poll", "по Y"))
        self.label_8.setText(_translate("Set_poll", "по X"))
        self.save_set.setText(_translate("Set_poll", "Сохранить"))
        self.set_Formyl.setHtml(_translate("Set_poll", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_9.setToolTip(_translate("Set_poll", "Пространственное уравнение без знака равенства"))
        self.label_9.setText(_translate("Set_poll", "Уравнение,\n"
" задающее \n"
" загрязнение"))
