# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Анна\Desktop\ANNA\dip.rab2\Color.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainColor(object):
    def setupUi(self, MainColor):
        MainColor.setObjectName("MainColor")
        MainColor.resize(281, 447)
        self.centralwidget = QtWidgets.QWidget(MainColor)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 30, 241, 21))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../1.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(250, 100))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 60, 241, 21))
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../2.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(250, 100))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 90, 241, 21))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../3.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(250, 100))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 120, 241, 21))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../4.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(250, 100))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 150, 241, 21))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../5.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(250, 100))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 180, 241, 21))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../6.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon5)
        self.pushButton_6.setIconSize(QtCore.QSize(250, 100))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 210, 241, 21))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../7.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon6)
        self.pushButton_7.setIconSize(QtCore.QSize(250, 100))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 240, 241, 21))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../10.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon7)
        self.pushButton_8.setIconSize(QtCore.QSize(250, 100))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(20, 270, 241, 21))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../../11.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon8)
        self.pushButton_9.setIconSize(QtCore.QSize(250, 100))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(20, 300, 241, 21))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../../12.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon9)
        self.pushButton_10.setIconSize(QtCore.QSize(250, 16100))
        self.pushButton_10.setObjectName("pushButton_10")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 0, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(20, 330, 241, 21))
        self.pushButton_11.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../../13.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon10)
        self.pushButton_11.setIconSize(QtCore.QSize(250, 16100))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(20, 360, 241, 21))
        self.pushButton_12.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../../15.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon11)
        self.pushButton_12.setIconSize(QtCore.QSize(250, 16100))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(20, 390, 241, 21))
        self.pushButton_13.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../../16.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_13.setIcon(icon12)
        self.pushButton_13.setIconSize(QtCore.QSize(250, 16100))
        self.pushButton_13.setObjectName("pushButton_13")
        MainColor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainColor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 281, 21))
        self.menubar.setObjectName("menubar")
        MainColor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainColor)
        self.statusbar.setObjectName("statusbar")
        MainColor.setStatusBar(self.statusbar)

        self.retranslateUi(MainColor)
        QtCore.QMetaObject.connectSlotsByName(MainColor)

    def retranslateUi(self, MainColor):
        _translate = QtCore.QCoreApplication.translate
        MainColor.setWindowTitle(_translate("MainColor", "Выбор цвета"))
        self.pushButton_3.setText(_translate("MainColor", " "))
        self.pushButton_4.setText(_translate("MainColor", " "))
        self.pushButton_5.setText(_translate("MainColor", " "))
        self.pushButton_6.setText(_translate("MainColor", " "))
        self.pushButton_7.setText(_translate("MainColor", " "))
        self.pushButton_8.setText(_translate("MainColor", " "))
        self.pushButton_9.setText(_translate("MainColor", " "))
        self.pushButton_10.setText(_translate("MainColor", " "))
        self.label.setText(_translate("MainColor", "Выберите цвет для графика"))


