# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Анна\Desktop\ANNA\dip.rab2\forma.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(357, 529)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("science.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.grid = QtWidgets.QTextEdit(self.centralwidget)
        self.grid.setEnabled(False)
        self.grid.setGeometry(QtCore.QRect(10, 40, 171, 31))
        self.grid.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.grid.setObjectName("grid")
        self.poll = QtWidgets.QTextEdit(self.centralwidget)
        self.poll.setEnabled(False)
        self.poll.setGeometry(QtCore.QRect(10, 110, 171, 51))
        self.poll.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.poll.setObjectName("poll")
        self.layer = QtWidgets.QTextEdit(self.centralwidget)
        self.layer.setEnabled(True)
        self.layer.setGeometry(QtCore.QRect(10, 300, 141, 31))
        self.layer.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.layer.setObjectName("layer")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 280, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.textEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_5.setEnabled(True)
        self.textEdit_5.setGeometry(QtCore.QRect(180, 410, 141, 31))
        self.textEdit_5.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textEdit_5.setObjectName("textEdit_5")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(180, 380, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(280, 450, 51, 51))
        self.start.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.start.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("power-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start.setIcon(icon1)
        self.start.setIconSize(QtCore.QSize(40, 40))
        self.start.setObjectName("start")
        self.reset = QtWidgets.QPushButton(self.centralwidget)
        self.reset.setGeometry(QtCore.QRect(190, 450, 52, 48))
        self.reset.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.reset.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reset.setIcon(icon2)
        self.reset.setIconSize(QtCore.QSize(40, 40))
        self.reset.setObjectName("reset")
        self.excel = QtWidgets.QPushButton(self.centralwidget)
        self.excel.setGeometry(QtCore.QRect(20, 450, 51, 51))
        self.excel.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.excel.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("paper.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.excel.setIcon(icon3)
        self.excel.setIconSize(QtCore.QSize(40, 40))
        self.excel.setObjectName("excel")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 260, 361, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.set_poll = QtWidgets.QPushButton(self.centralwidget)
        self.set_poll.setGeometry(QtCore.QRect(260, 110, 61, 61))
        self.set_poll.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.set_poll.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.set_poll.setIcon(icon4)
        self.set_poll.setIconSize(QtCore.QSize(40, 40))
        self.set_poll.setObjectName("set_poll")
        self.set_grid = QtWidgets.QPushButton(self.centralwidget)
        self.set_grid.setGeometry(QtCore.QRect(260, 20, 61, 61))
        self.set_grid.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.set_grid.setText("")
        self.set_grid.setIcon(icon4)
        self.set_grid.setIconSize(QtCore.QSize(40, 40))
        self.set_grid.setObjectName("set_grid")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 380, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.textEdit_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_6.setEnabled(False)
        self.textEdit_6.setGeometry(QtCore.QRect(10, 410, 141, 31))
        self.textEdit_6.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textEdit_6.setObjectName("textEdit_6")
        self.bias = QtWidgets.QTextEdit(self.centralwidget)
        self.bias.setEnabled(False)
        self.bias.setGeometry(QtCore.QRect(10, 200, 171, 51))
        self.bias.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.bias.setObjectName("bias")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 170, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(160, 300, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(230, 300, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(300, 300, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setAutoFillBackground(False)
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(10, 350, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.set_color = QtWidgets.QPushButton(self.centralwidget)
        self.set_color.setGeometry(QtCore.QRect(100, 450, 61, 61))
        self.set_color.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.set_color.setText("")
        self.set_color.setIcon(icon4)
        self.set_color.setIconSize(QtCore.QSize(40, 40))
        self.set_color.setObjectName("set_color")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 357, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Модель распространения загрязнения"))
        self.label.setText(_translate("MainWindow", "Размерность сетки"))
        self.label_2.setText(_translate("MainWindow", "Размерность загрязнения"))
        self.grid.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.poll.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.layer.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Выведенный слой"))
        self.textEdit_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "Количество итераций"))
        self.label_6.setText(_translate("MainWindow", "Итерации"))
        self.textEdit_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.bias.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Смещение относительно центра"))
        self.radioButton.setText(_translate("MainWindow", "по X"))
        self.radioButton_2.setText(_translate("MainWindow", "по Y"))
        self.radioButton_3.setText(_translate("MainWindow", "по Z"))
        self.checkBox.setText(_translate("MainWindow", "Визуализация"))


